export const siteConfig = {
  name: "Anis Bouchema",
  title: "Business Technology Management Student & Franchise Operator",
  description: "Portfolio website of Anis Bouchema",
  accentColor: "#2b3fff",
  social: {
    email: "anis.bouchema@torontomu.ca",
    linkedin: "https://linkedin.com/in/anis-bouchema",
  },
  aboutMe:
    "I'm a Business Technology Management student at Toronto Metropolitan University with hands-on experience running two franchise dessert retail locations generating over $550K in annual revenue. Since 2019, I've grown from Ice Cream Server to General Manager to Business Operator — and in 2022, I launched the High Park (Bloor) location end-to-end, from site selection and lease negotiation through hiring, training, and opening day. Day to day, I manage staffing, inventory planning, supplier relationships, and performance reporting across both sites. I build Excel dashboards from POS exports to track sales trends, labor efficiency, product mix, and variances — then translate those numbers into action plans. I've developed real P&L responsibility as an undergrad, which shapes how I think about every decision. Outside of operations, I founded the Sustainable Business Association at TMU from scratch, building the team, systems, and partner pipeline needed to run events with 80+ attendees. I'm interested in roles that combine business and technology: operations analytics, business analysis, financial reporting, process improvement, and data storytelling.",
  skills: [
    "Microsoft Excel (Advanced)",
    "Financial Modeling & Reporting",
    "Inventory & Supply Chain Management",
    "Workforce Planning & Scheduling",
    "Business Analytics",
    "Data Visualization",
    "Operations Management",
    "Process Automation",
    "Strategic Planning",
    "AI & Automation Tools",
    "Machine Learning Fundamentals",
    "Python (Fundamentals)",
    "Power BI",
    "Power Automate",
    "SharePoint Online",
    "Financial Analysis",
    "KPI Reporting",
    "Variance Analysis",
    "Forecasting",
    "Inventory Planning",
    "Process Improvement",
    "Data Storytelling",
    "Stakeholder Management",
    "Project Coordination",
    "People Management",
    "English (Fluent)",
    "French (Fluent)",
  ],
  projects: [
    {
      name: "La Diperie — Dual-Location Inventory Optimization Model",
      category: "Operations & Supply Chain",
      tag: "Operations",
      description:
        "Built a multi-sheet Excel workbook to coordinate inventory across La Diperie Oakville and High Park. Covers 262 SKUs — calculates par levels, safety stock, and reorder points, generates inter-store transfer suggestions, tracks shared bulk orders, and produces a settlement summary. Includes a Low Cash Mode that enforces spending caps.",
      link: "",
      skills: [
        "Excel",
        "Inventory Planning",
        "Supply Chain",
        "Operations Management",
        "Data Modeling",
        "Process Automation",
      ],
    },
    {
      name: "La Diperie & La Fayette — 16-Week Resource Scheduler",
      category: "Workforce Planning",
      tag: "Scheduling",
      description:
        "Designed a 16-week staffing and capacity planner for a team of 7 across three businesses — La Diperie Oakville, La Diperie High Park, and La Fayette coffee shop. Tracks weekly demand vs. capacity per person, flags over-allocation, manages 29 tasks across 7 projects, and surfaces staffing gaps during peak season.",
      link: "",
      skills: [
        "Excel",
        "Workforce Planning",
        "Capacity Modeling",
        "Multi-Site Operations",
        "Scheduling Automation",
        "Data Validation",
      ],
    },
    {
      name: "La Diperie — Financial Reporting Dashboard (FY 2024–2025)",
      category: "Finance & Analytics",
      tag: "Finance",
      description:
        "Consolidated financial dashboard for two La Diperie locations on a $550K+ revenue base. Includes a full monthly P&L, revenue trend tracking by location, cash flow forecast, EBITDA and net margin tracking, variance alerts against budget, and KPI flags including YoY growth and average order value.",
      link: "",
      skills: [
        "Excel",
        "Financial Modeling",
        "P&L Analysis",
        "Cash Flow Forecasting",
        "Business Analytics",
        "Data Visualization",
      ],
    },
  ],
  experience: [
    {
      company: "La Diperie (Oakville & Toronto, ON)",
      title: "Business Operator",
      dateRange: "2021 – Present",
      bullets: [
        "Operate two dessert retail franchise locations generating $550K+ in annual revenue with full P&L responsibility across staffing, inventory, supplier relationships, and financial reporting.",
        "Built weekly and monthly KPI reporting from POS exports to track sales trends, product mix, and peak periods; developed Excel dashboards using pivot tables, lookups, conditional formatting, and charts.",
        "Implemented inventory planning logic — reorder points, safety stock, and EOQ triggers — to reduce waste and improve in-stock performance.",
        "Led hiring, scheduling, and coaching for 10+ staff; created SOPs and training checklists to standardize execution across both sites.",
        "Planned and launched the High Park (Bloor) location end-to-end in 2022: site selection, lease negotiation, vendor coordination, team recruitment, onboarding, and operational controls.",
      ],
    },
    {
      company: "Sustainable Business Association (SBA), TMU",
      title: "Founder & President",
      dateRange: "2024 – Present",
      bullets: [
        "Founded SBA from zero and built the initial strategy: mission, target member segments, value proposition, and semester roadmap.",
        "Recruited and onboarded the executive team; defined org structure, role scopes, and weekly execution cadence.",
        "Built a partner and sponsorship pipeline: prospect research, segmentation, outreach messaging, and follow-up tracking across 50+ potential sponsors.",
        "Owned event delivery end-to-end — budgeting, venue logistics, run-of-show, risk checks, and post-event feedback — for events with 80+ attendees.",
      ],
    },
    {
      company: "Toronto Met Entrepreneurship Association (TEA)",
      title: "General Associate",
      dateRange: "2024 – Present",
      bullets: [
        "Support HR tasks: role coordination, scheduling, onboarding help, and internal documentation.",
        "Assist marketing execution: drafting posts, outreach messages, and event materials.",
        "Conduct market and competitor research; summarize findings into clear notes for decision-making.",
        "Build structured documentation and trackers — task lists, timelines, meeting notes — to keep projects organized.",
      ],
    },
    {
      company: "Conseil scolaire Viamonde",
      title: "French Tutor / Program Coordinator",
      dateRange: "2023 – Present",
      bullets: [
        "Deliver bilingual (French/English) 1:1 and small-group tutoring for Grades 1–6 across French and core subjects.",
        "Coordinate scheduling and assignment of other tutors; manage availability and balance coverage across 14 classes.",
        "Streamlined tutoring delivery by standardizing lesson templates, pacing plans, and progress logs to improve consistency and reduce admin time.",
      ],
    },
  ],
  education: [
    {
      school: "Toronto Metropolitan University — Ted Rogers School of Management",
      degree: "Bachelor of Commerce, Business Technology Management",
      dateRange: "2024 – 2028 (Expected)",
      achievements: [
        "Top 10% Engaged (2024/2025) — Ted Rogers 'Fit for Business'",
        "Relevant Coursework: Data Analytics, Finance, Marketing, Systems Analysis & Design, Organizational Behaviour",
        "Founder & President, Sustainable Business Association",
      ],
    },
  ],
};
